---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Update package cache"
      ansible.builtin.apt:
        update_cache: yes
    - name: "Include ansible-slurm"
      include_role:
        name: "ansible-slurm"
        
  vars:
    slurm_roles: ['controller', 'exec', 'dbd']
    storage_type: ''